### ISSUE TITLE
Clean up open branches that are not PRs

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/covid-19-procurement-explorer-admin#217]
Either create PRs or delete the branches.

https://github.com/open-contracting/covid-19-procurement-explorer-admin/branches/all

**Comment by jpmckinney** [comment]
There is only one left, so it's okay.

**Comment by jpmckinney** [comment]
Actually, @KushalRaj can you explain this branch? Should there be a PR? https://github.com/open-contracting/covid-19-procurement-explorer-admin/tree/admin-template-edit

**Comment by KushalRaj** [comment]
Yes @jpmckinney  that branch can be deleted. Changes of that branch were merged into main from another branch. I will delete the branch. No need for a PR.
