### ISSUE TITLE
Refactor Visualization API

### ISSUE THREAD

**Issue by KushalRaj** [open-contracting/covid-19-procurement-explorer-admin#284]
- [ ] Average Bids
- [ ] Buyer Detail
- [ ] Buyer Trend
- [ ] Buyers
- [ ] Contracts
- [ ] Contracts Coorelation
- [ ] Country Suppliers
- [ ] Direct / Open
- [ ] Direct/Open Contract Trend
- [ ] Equity Indicators
- [ ] Equity Summary
- [ ] Global Suppiers
- [ ] Monopolization
- [ ] Overall Statistics
- [ ] Product
- [ ] Product Distribution
- [ ] Product Flow
- [ ] Product List
- [ ] Product Spending Comparison
- [ ] Product Summary
- [ ] Product Timeline
- [ ] Product Timeline Race
- [ ] Product wise World Map
- [ ] Red Flag Summary
- [ ] Supplier Detail
- [ ] Supplier Product Flow
- [ ] Supplier Trend
- [ ] Suppliers
- [x] Top Buyers
- [x] Top Suppliers
- [x] Total Contracts
- [x] Total Spending
- [ ] World Map
- [x] World Map Race

**Comment by sonikabaniya** [comment]
What do you mean by red flag "4,8" @KushalRaj ?
