### ISSUE TITLE
Set Buyer / Supplier summary 

### ISSUE THREAD

**Issue by KushalRaj** [open-contracting/covid-19-procurement-explorer-admin#295]
- [x] Create buyer and supplier summary commands/tasks like `summarize_buyer` and `summarize_supplier`
- [x] Command will take buyer id or supplier id as parameter
- [x] Add a `summary` JSON column in `country_buyer` and `country_supplier` tables
- [x] Calculate summary information of buyer and supplier like:
- [x] number of contracts `tender_count`
- [x] total `amount_usd`
- [x] total `amount_local`
- [x] number of unique suppliers `supplier_count` OR buyers `buyer_count`
- [x] number of Product categories `product_count`
- [x] total of contracts with red flag `red_flag_tender_count`
- [x] percentage of contracts with red flag `red_flag_tender_percentage`

**Comment by suyojman** [comment]
Command will take buyer id or supplier id as parameter ?? Only id not country?? @KushalRaj
