### ISSUE TITLE
Overall Summary add columns

### ISSUE THREAD

**Issue by sonikabaniya** [open-contracting/covid-19-procurement-explorer-admin#314]
- [x] No of Buyers
- [x] No of Suppliers
- [ ] Average bids per contract
- [ ] Monopolization
- [x] quantity of red flags
- [x] total value of contracts with red flags
- [x] quantity of equity contracts
- [x] total value of equity contracts
- [ ] total value per product category
- [x] Time span
- [x] GDP per captia
- [x] healthcare budget
- [x] % of GDP to healthcare budget
- [ ] $ per covid case
- [ ] Covid statistics per country Active cases, current
- [ ] Covid statistics per country Total cases
- [ ] Total death cases, cumulative

**Comment by jpmckinney** [comment]
I assume that this feature will not be implemented, at this point, so closing.
