### ISSUE TITLE
CMS issues as per client feedback

### ISSUE THREAD

**Issue by KushalRaj** [open-contracting/covid-19-procurement-explorer-admin#40]
- [x] Remove Parent page selection when adding Insight content #urgent
- [x] Remove Body from Insights list and add columns for created at, author and tags #urgent
- [x] Content action like Preview and Publish is resulting an error #urgent (needs more clarification on this)
- [x] Remove unused functions like Workflows, Reports sections, etc.
- [x] Add boolean field titled as "Featured" to highlight content (news, blogs)
- [ ] Featured to add predefined tags to avoid duplication and make easy for content writers
- [x] Add content pages like About Us, Terms of Use, etc.
- [x] Add a country item as Global for global contents

**Comment by sonikabaniya** [comment]
This issue has been addressed and fixed. As per discussion in our meeting, we decided to hold tag part for now. So, closing it for now
