### ISSUE TITLE
CMS - News & Blogs

### ISSUE THREAD

**Issue by KushalRaj** [open-contracting/covid-19-procurement-explorer-admin#51]
- [x] Show Country name in table
- [x] Tags are not shown in Tags column

In content preview,
- [x] body content should be parse as HTML
- [x] show tags
- [x] show content title as page title; we have title as 'Page Title'
- [x] remove _ after twitter share icon
- [x] remove . after month in Published on date

**Comment by sonikabaniya** [comment]
@KushalRaj dai, are we good to close this issue?
